// routes/qrroutes.js
import express from "express";
import {
  generateQRApi,
  getInfoById,
  updateInfoById,
  getAllRecords,
  generateLoadTicketQR,
  generateDisposalTicket,
} from "../controller/qrcontroller.js";

const router = express.Router();

router.post("/api/generate", generateQRApi);
router.get("/api/info/:id", getInfoById);
router.put("/api/info/:id", updateInfoById);

// optional history route for debugging/inspection
router.get("/records", getAllRecords);

/* Filed Monitor (Load Ticket) */
router.post("/api/generateloadticket", generateLoadTicketQR);
router.post("/api/generatedisposalticket", generateDisposalTicket);

router.get("/api/schema/truck-cert", async (req, res) => {
  res.json({
    formId: "truck-certification-form-v2",
    title: "Truck Certification Form",
    version: 2.0,
    createdAt: "2025-11-10T10:00:00Z",
    updatedAt: "2025-11-10T20:00:00Z",
    totalSections: 19,
    sections: [
      {
        sectionId: "section_2_vehicle_type",
        title: "Vehicle Type",
        order: 2,
        fields: [
          {
            fieldId: "vehicle_type_selector",
            name: "vehicle_type_selector",
            type: "customSelector",
            label: "Select Vehicle Type",
            required: true,
            editable: true,
            defaultValue: "truck",
            options: [
              {
                label: "Truck",
                value: "truck",
                nextSectionId: "section_3_truck_owner_details",
              },
              {
                label: "Equipment",
                value: "equipment",
                nextSectionId: "section_3_equipment_owner_details",
              },
              {
                label: "Roll-Off",
                value: "roll_off",
                nextSectionId: "section_3_rolloff_company_details",
              },
            ],
          },
        ],
      },
      {
        sectionId: "section_3_truck_owner_details",
        title: "Driver & Owner Details",
        order: 3,
        fields: [
          {
            fieldId: "driver_first_name",
            name: "driver_first_name",
            type: "text",
            label: "Driver First Name",
            placeholder: "Enter Driver Name",
            required: true,
            editable: true,
          },
          {
            fieldId: "driver_last_name",
            name: "driver_last_name",
            type: "text",
            label: "Driver Last Name",
            placeholder: "Enter Driver Name",
            required: true,
            editable: true,
          },
          {
            fieldId: "driving_license_upload",
            name: "driving_license_upload",
            type: "imageUpload",
            label: "Driving License",
            required: true,
            editable: true,
            config: { maxFiles: 1, allowedTypes: ["image/jpeg", "image/png"] },
          },
          {
            fieldId: "license_state",
            name: "license_state",
            type: "dropdown",
            label: "License State",
            placeholder: "Select",
            required: false,
            editable: true,
            options: {
              type: "static",
              data: [
                { label: "Alabama", value: "alabama" },
                { label: "Alaska", value: "alaska" },
                { label: "Arizona", value: "arizona" },
                { label: "Arkansas", value: "arkansas" },
                { label: "California", value: "california" },
                { label: "Colorado", value: "colorado" },
                { label: "Connecticut", value: "connecticut" },
                { label: "Delaware", value: "delaware" },
                { label: "Florida", value: "florida" },
                { label: "Georgia", value: "georgia" },
                { label: "Hawaii", value: "hawaii" },
                { label: "Idaho", value: "idaho" },
                { label: "Illinois", value: "illinois" },
                { label: "Indiana", value: "indiana" },
                { label: "Iowa", value: "iowa" },
                { label: "Kansas", value: "kansas" },
                { label: "Kentucky", value: "kentucky" },
                { label: "Louisiana", value: "louisiana" },
                { label: "Maine", value: "maine" },
                { label: "Maryland", value: "maryland" },
                { label: "Massachusetts", value: "massachusetts" },
                { label: "Michigan", value: "michigan" },
                { label: "Minnesota", value: "minnesota" },
                { label: "Mississippi", value: "mississippi" },
                { label: "Missouri", value: "missouri" },
                { label: "Montana", value: "montana" },
                { label: "Nebraska", value: "nebraska" },
                { label: "Nevada", value: "nevada" },
                { label: "New Hampshire", value: "new_hampshire" },
                { label: "New Jersey", value: "new_jersey" },
                { label: "New Mexico", value: "new_mexico" },
                { label: "New York", value: "new_york" },
                { label: "North Carolina", value: "north_carolina" },
                { label: "North Dakota", value: "north_dakota" },
                { label: "Ohio", value: "ohio" },
                { label: "Oklahoma", value: "oklahoma" },
                { label: "Oregon", value: "oregon" },
                { label: "Pennsylvania", value: "pennsylvania" },
                { label: "Rhode Island", value: "rhode_island" },
                { label: "South Carolina", value: "south_carolina" },
                { label: "South Dakota", value: "south_dakota" },
                { label: "Tennessee", value: "tennessee" },
                { label: "Texas", value: "texas" },
                { label: "Utah", value: "utah" },
                { label: "Vermont", value: "vermont" },
                { label: "Virginia", value: "virginia" },
                { label: "Washington", value: "washington" },
                { label: "West Virginia", value: "west_virginia" },
                { label: "Wisconsin", value: "wisconsin" },
                { label: "Wyoming", value: "wyoming" },
              ],
            },
          },
          {
            fieldId: "license_expiration_date",
            name: "license_expiration_date",
            type: "date",
            label: "License Expiration Date",
            placeholder: "MM/DD/YYYY",
            required: true,
            editable: true,
          },
          {
            fieldId: "insurance_card_upload",
            name: "insurance_card_upload",
            type: "imageUpload",
            label: "Insurance Card",
            required: true,
            editable: true,
            config: {
              maxFiles: 1,
              allowedTypes: ["image/jpeg", "image/png", "application/pdf"],
            },
          },
          {
            fieldId: "driver_company_name",
            name: "driver_company_name",
            type: "text",
            label: "Company",
            placeholder: "Enter",
            required: true,
            editable: true,
          },
          {
            fieldId: "driver_email",
            name: "driver_email",
            type: "email",
            label: "Email",
            placeholder: "Enter",
            required: false,
            editable: true,
          },
          {
            fieldId: "driver_phone",
            name: "driver_phone",
            type: "phone",
            label: "Phone",
            placeholder: "Enter",
            required: true,
            editable: true,
          },
          {
            fieldId: "is_driver_owner",
            name: "is_driver_owner",
            type: "toggle",
            label: "Driver is Owner",
            required: false,
            editable: true,
            defaultValue: false,
            options: [
              { label: "Yes", value: true },
              { label: "No", value: false },
            ],
          },
          {
            fieldId: "owner_first_name",
            name: "owner_first_name",
            type: "text",
            label: "Owner First Name",
            placeholder: "Enter Owner First Name",
            required: false,
            editable: true,
            dependencies: [
              {
                fieldId: "is_driver_owner",
                condition: "equals",
                value: false,
                actions: [{ action: "show" }],
              },
            ],
          },
          {
            fieldId: "owner_last_name",
            name: "owner_last_name",
            type: "text",
            label: "Owner Last Name",
            placeholder: "Enter Owner Last Name",
            required: false,
            editable: true,
            dependencies: [
              {
                fieldId: "is_driver_owner",
                condition: "equals",
                value: false,
                actions: [{ action: "show" }],
              },
            ],
          },
          {
            fieldId: "owner_company_name",
            name: "owner_company_name",
            type: "text",
            label: "Owner Company Name",
            placeholder: "Enter Owner Company Name",
            required: true,
            editable: true,
            dependencies: [
              {
                fieldId: "is_driver_owner",
                condition: "equals",
                value: false,
                actions: [{ action: "show" }],
              },
            ],
          },
          {
            fieldId: "owner_email",
            name: "owner_email",
            type: "email",
            label: "Email",
            placeholder: "Enter",
            required: false,
            editable: true,
            dependencies: [
              {
                fieldId: "is_driver_owner",
                condition: "equals",
                value: false,
                actions: [{ action: "show" }],
              },
            ],
          },
          {
            fieldId: "owner_telephone",
            name: "owner_telephone",
            type: "phone",
            label: "Telephone",
            placeholder: "(000) 000-0000",
            required: false,
            editable: true,
            dependencies: [
              {
                fieldId: "is_driver_owner",
                condition: "equals",
                value: false,
                actions: [{ action: "show" }],
              },
            ],
          },
        ],
        nextSectionId: "section_4_truck_type",
      },
      {
        sectionId: "section_3_equipment_owner_details",
        title: "Owner & Company Details",
        order: 3,
        fields: [
          {
            fieldId: "company_name",
            name: "company_name",
            type: "text",
            label: "Company Name",
            placeholder: "Enter",
            required: true,
            editable: true,
          },
          {
            fieldId: "company_email",
            name: "company_email",
            type: "email",
            label: "Email",
            placeholder: "Enter",
            required: false,
            editable: true,
          },
          {
            fieldId: "company_phone",
            name: "company_phone",
            type: "phone",
            label: "Phone",
            placeholder: "Enter",
            required: true,
            editable: true,
          },
          {
            fieldId: "owner_first_name",
            name: "owner_first_name",
            type: "text",
            label: "Owner First Name",
            placeholder: "Enter Owner First Name",
            required: false,
            editable: true,
          },
          {
            fieldId: "owner_last_name",
            name: "owner_last_name",
            type: "text",
            label: "Owner Last Name",
            placeholder: "Enter Owner Last Name",
            required: false,
            editable: true,
          },
          {
            fieldId: "owner_company_name",
            name: "owner_company_name",
            type: "text",
            label: "Owner Company Name",
            placeholder: "Enter Owner Company Name",
            required: true,
            editable: true,
          },
          {
            fieldId: "owner_email",
            name: "owner_email",
            type: "email",
            label: "Owner Email",
            placeholder: "Enter",
            required: false,
            editable: true,
          },
          {
            fieldId: "owner_phone",
            name: "owner_phone",
            type: "phone",
            label: "Owner Phone",
            placeholder: "(000) 000-0000",
            required: false,
            editable: true,
          },
        ],
        nextSectionId: "section_4_equipment_type",
      },
      {
        sectionId: "section_3_rolloff_company_details",
        title: "Owner & Company Details",
        order: 3,
        fields: [
          {
            fieldId: "company_name",
            name: "company_name",
            type: "text",
            label: "Company Name",
            placeholder: "Enter",
            required: true,
            editable: true,
          },
          {
            fieldId: "company_email",
            name: "company_email",
            type: "email",
            label: "Email",
            placeholder: "Enter",
            required: false,
            editable: true,
          },
          {
            fieldId: "company_phone",
            name: "company_phone",
            type: "phone",
            label: "Phone",
            placeholder: "Enter",
            required: true,
            editable: true,
          },
        ],
        nextSectionId: "section_4_rolloff_type",
      },
      {
        sectionId: "section_4_truck_type",
        title: "Truck Type",
        order: 4,
        fields: [
          {
            fieldId: "truck_type_selector",
            name: "truck_type_selector",
            type: "customSelector",
            label: "Select Truck Type:",
            required: true,
            editable: true,
            defaultValue: "pickup_truck",
            options: [
              {
                label: "Pickup Truck",
                value: "pickup_truck",
                icon: {
                  url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/bb297f50ea4ce157b617a8ed841f563a73954436.png",
                },
              },
              {
                label: "Self Loader",
                value: "self_loader",
                icon: {
                  url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/437180b35f24a0474bff24287b9a857d67413c77.png",
                },
              },
              {
                label: "Tandem Trailer",
                value: "tandem_trailer",
                icon: {
                  url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/0e1c24071b1bdde2e4291dce5db3f6d51c378641.png",
                },
              },
              {
                label: "Walking Floor",
                value: "walking_floor",
                icon: {
                  url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/1d05124147fd395c622687356811e24ca6b647f5.png",
                },
              },
              {
                label: "Dump Trailer",
                value: "dump_trailer",
                icon: {
                  url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/cf0c033bceac4db8213b2815df389dfe668dd8b8.png",
                },
              },
              {
                label: "Dump Truck",
                value: "dump_truck",
                icon: {
                  url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/fe23585680c5ebd972849e412e4146ff46fcc043.png",
                },
              },
              {
                label: "Bucket Truck",
                value: "bucket_truck",
                icon: {
                  url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/5c3f2dfd7b8f9a46de19133adc7140f24f4dfb9e.png",
                },
              },
              {
                label: "Flatbed Trailer",
                value: "flatbed_trailer",
                icon: {
                  url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/d8997f407292e085d9b8754db35137947447158e.png",
                },
              },
              {
                label: "Flatbed Truck",
                value: "flatbed_truck",
                icon: {
                  url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/5acbe193e6b09e7c6262aaff7405993d545fbe47.png",
                },
              },
            ],
          },
        ],
        nextSectionId: "section_5_truck_details",
      },
      {
        sectionId: "section_4_equipment_type",
        title: "Equipment Type",
        order: 4,
        fields: [
          {
            fieldId: "equipment_type_selector",
            name: "equipment_type_selector",
            type: "customSelector",
            label: "Select Equipment Type:",
            required: true,
            editable: true,
            defaultValue: "jarraff_tree_saw",
            options: [
              {
                label: "Jarraff Tree Saw",
                value: "jarraff_tree_saw",
                icon: {
                  url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/e88116163aa0634428a7117de59117d09232025d.png",
                },
              },
              {
                label: "Skid Steer",
                value: "skid_steer",
                icon: {
                  url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/ce0800685fb52e01c29a20ff3d7205daab12cede.png",
                },
              },
              {
                label: "Tractor",
                value: "tractor",
                icon: {
                  url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/56e77444587588c867beeced6ec0481b3ad474b7.png",
                },
              },
              {
                label: "Wheel Loader",
                value: "wheel_loader",
                icon: {
                  url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/af11d15c89def63130831c7c97e60bf27c0db61d.png",
                },
              },
              {
                label: "Barge",
                value: "barge",
                icon: {
                  url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/af11d15c89def63130831c7c97e60bf27c0db61d.png",
                },
              },
              {
                label: "Excavator",
                value: "excavator",
                icon: {
                  url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/c7803c4d926d7d94f91b96669c53e31eef2df228.png",
                },
              },
            ],
          },
        ],
        nextSectionId: "section_5_equipment_details",
      },
      {
        sectionId: "section_4_rolloff_type",
        title: "Roll-Off Type",
        order: 4,
        fields: [
          {
            fieldId: "equipment_type_selector",
            name: "equipment_type_selector",
            type: "customSelector",
            label: "Select Equipment Type:",
            required: true,
            editable: true,
            defaultValue: "jarraff_tree_saw",
            options: [
              {
                label: "Roll Off Container 1",
                value: "roll_off_container_1",
                icon: {
                  url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/Roll-Off%20Container%20Pic%201.png",
                },
              },
              {
                label: "Roll Off Container 2",
                value: "roll_off_container_2",
                icon: {
                  url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/Roll-Off%20Container%20Pic%202.png",
                },
              },
              {
                label: "Roll off Container 3",
                value: "roll_off_container_3",
                icon: {
                  url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/Roll-Off%20Container%20Pic%203.png",
                },
              },
            ],
          },
        ],
        nextSectionId: "section_5_rolloff_details",
      },
      {
        sectionId: "section_5_truck_details",
        title: "Truck Details",
        order: 5,
        fields: [
          {
            fieldId: "truck_make",
            name: "truck_make",
            type: "text",
            label: "Make",
            placeholder: "Enter Make",
            required: true,
            editable: true,
          },
          {
            fieldId: "truck_model",
            name: "truck_model",
            type: "text",
            label: "Model",
            placeholder: "Enter Model",
            required: true,
            editable: true,
          },
          {
            fieldId: "truck_year",
            name: "truck_year",
            type: "date",
            label: "Year",
            placeholder: "YYYY",
            required: true,
            editable: true,
          },
          {
            fieldId: "vin_number_upload",
            name: "vin_number_upload",
            type: "imageUpload",
            label: "VIN Number",
            required: true,
            editable: true,
            config: { maxFiles: 1, allowedTypes: ["image/jpeg", "image/png"] },
          },
          {
            fieldId: "truck_color",
            name: "truck_color",
            type: "text",
            label: "Color",
            placeholder: "Enter",
            required: true,
            editable: true,
          },
          {
            fieldId: "tag_state",
            name: "tag_state",
            type: "dropdown",
            label: "Tag State",
            placeholder: "Select",
            required: true,
            editable: true,
            options: {
              type: "static",
              data: [
                { label: "Alabama", value: "alabama" },
                { label: "Alaska", value: "alaska" },
                { label: "Arizona", value: "arizona" },
                { label: "Arkansas", value: "arkansas" },
                { label: "California", value: "california" },
                { label: "Colorado", value: "colorado" },
                { label: "Connecticut", value: "connecticut" },
                { label: "Delaware", value: "delaware" },
                { label: "Florida", value: "florida" },
                { label: "Georgia", value: "georgia" },
                { label: "Hawaii", value: "hawaii" },
                { label: "Idaho", value: "idaho" },
                { label: "Illinois", value: "illinois" },
                { label: "Indiana", value: "indiana" },
                { label: "Iowa", value: "iowa" },
                { label: "Kansas", value: "kansas" },
                { label: "Kentucky", value: "kentucky" },
                { label: "Louisiana", value: "louisiana" },
                { label: "Maine", value: "maine" },
                { label: "Maryland", value: "maryland" },
                { label: "Massachusetts", value: "massachusetts" },
                { label: "Michigan", value: "michigan" },
                { label: "Minnesota", value: "minnesota" },
                { label: "Mississippi", value: "mississippi" },
                { label: "Missouri", value: "missouri" },
                { label: "Montana", value: "montana" },
                { label: "Nebraska", value: "nebraska" },
                { label: "Nevada", value: "nevada" },
                { label: "New Hampshire", value: "new_hampshire" },
                { label: "New Jersey", value: "new_jersey" },
                { label: "New Mexico", value: "new_mexico" },
                { label: "New York", value: "new_york" },
                { label: "North Carolina", value: "north_carolina" },
                { label: "North Dakota", value: "north_dakota" },
                { label: "Ohio", value: "ohio" },
                { label: "Oklahoma", value: "oklahoma" },
                { label: "Oregon", value: "oregon" },
                { label: "Pennsylvania", value: "pennsylvania" },
                { label: "Rhode Island", value: "rhode_island" },
                { label: "South Carolina", value: "south_carolina" },
                { label: "South Dakota", value: "south_dakota" },
                { label: "Tennessee", value: "tennessee" },
                { label: "Texas", value: "texas" },
                { label: "Utah", value: "utah" },
                { label: "Vermont", value: "vermont" },
                { label: "Virginia", value: "virginia" },
                { label: "Washington", value: "washington" },
                { label: "West Virginia", value: "west_virginia" },
                { label: "Wisconsin", value: "wisconsin" },
                { label: "Wyoming", value: "wyoming" },
              ],
            },
          },
          {
            fieldId: "tag_number",
            name: "tag_number",
            type: "text",
            label: "Tag Number",
            placeholder: "Enter",
            required: true,
            editable: true,
          },
          {
            fieldId: "tag_expiration_date",
            name: "tag_expiration_date",
            type: "date",
            label: "Tag Expiration Date",
            placeholder: "MM/DD/YYYY",
            required: true,
            editable: true,
          },
          {
            fieldId: "has_sideboards",
            name: "has_sideboards",
            type: "toggle",
            label: "Sideboards :",
            required: false,
            editable: true,
            defaultValue: true,
          },
          {
            fieldId: "has_open_back_mesh",
            name: "has_open_back_mesh",
            type: "toggle",
            label: "Open back/soft mesh:",
            required: false,
            editable: true,
            defaultValue: true,
          },
          {
            fieldId: "has_hand_loader",
            name: "has_hand_loader",
            type: "toggle",
            label: "Hand loader :",
            required: false,
            editable: true,
            defaultValue: true,
          },
          {
            fieldId: "comments",
            name: "comments",
            type: "textarea",
            label: "Comments",
            placeholder: "Add Notes",
            required: false,
            editable: true,
          },
        ],
        nextSectionId: "section_6_truck_photos",
      },
      {
        sectionId: "section_5_equipment_details",
        title: "Equipment Details",
        order: 5,
        fields: [
          {
            fieldId: "equipment_make",
            name: "equipment_make",
            type: "text",
            label: "Make",
            placeholder: "Enter Make",
            required: true,
            editable: true,
          },
          {
            fieldId: "equipment_model",
            name: "equipment_model",
            type: "text",
            label: "Model",
            placeholder: "Enter Model",
            required: true,
            editable: true,
          },
          {
            fieldId: "equipment_color",
            name: "equipment_color",
            type: "text",
            label: "Color",
            placeholder: "Enter",
            required: true,
            editable: true,
          },
          {
            fieldId: "equipment_comments",
            name: "equipment_comments",
            type: "textarea",
            label: "Comments",
            placeholder: "Add Notes",
            required: false,
            editable: true,
          },
        ],
        nextSectionId: "section_6_equipment_photos",
      },
      {
        sectionId: "section_5_rolloff_details",
        title: "Roll-Off Details",
        order: 5,
        fields: [
          {
            fieldId: "rolloff_make",
            name: "rolloff_make",
            type: "text",
            label: "Make",
            placeholder: "Enter Make",
            required: true,
            editable: true,
          },
          {
            fieldId: "rolloff_model",
            name: "rolloff_model",
            type: "text",
            label: "Model",
            placeholder: "Enter Model",
            required: true,
            editable: true,
          },
          {
            fieldId: "rolloff_color",
            name: "rolloff_color",
            type: "text",
            label: "Color",
            placeholder: "Enter",
            required: true,
            editable: true,
          },
          {
            fieldId: "rolloff_comments",
            name: "rolloff_comments",
            type: "textarea",
            label: "Comments",
            placeholder: "Add Notes",
            required: false,
            editable: true,
          },
        ],
        nextSectionId: "section_6_rolloff_photos",
      },
      {
        sectionId: "section_6_truck_photos",
        title: "Truck Photos",
        order: 6,
        fields: [
          {
            fieldId: "truck_front_view_upload",
            name: "truck_front_view_upload",
            type: "imageUpload",
            label: "Front View",
            required: true,
            editable: true,
            config: {
              maxFiles: 1,
              allowedTypes: ["image/jpeg", "image/png", "application/pdf"],
            },
          },
          {
            fieldId: "truck_side_view_upload",
            name: "truck_side_view_upload",
            type: "imageUpload",
            label: "Side View",
            required: true,
            editable: true,
            config: {
              maxFiles: 1,
              allowedTypes: ["image/jpeg", "image/png", "application/pdf"],
            },
          },
          {
            fieldId: "truck_back_view_upload",
            name: "truck_back_view_upload",
            type: "imageUpload",
            label: "Back View",
            required: true,
            editable: true,
            config: {
              maxFiles: 1,
              allowedTypes: ["image/jpeg", "image/png", "application/pdf"],
            },
          },
          {
            fieldId: "truck_numberplate_view_upload",
            name: "truck_numberplate_view_upload",
            type: "imageUpload",
            label: "Number Plate View",
            required: true,
            editable: true,
            config: {
              maxFiles: 1,
              allowedTypes: ["image/jpeg", "image/png", "application/pdf"],
            },
          },
        ],
        dependencies: [
          {
            conditionalNextSection: {
              basedOnField: "truck_type_selector",
              mapping: {
                bucket_truck: "review",
                flatbed_trailer: "review",
                flatbed_truck: "review",
              },
            },
          },
        ],
        nextSectionId: "section_7_container_shape",
      },
      {
        sectionId: "section_6_equipment_photos",
        title: "Equipment Photos",
        order: 6,
        fields: [
          {
            fieldId: "equipment_front_view_upload",
            name: "equipment_front_view_upload",
            type: "imageUpload",
            label: "Front View",
            required: true,
            editable: true,
            config: {
              maxFiles: 1,
              allowedTypes: ["image/jpeg", "image/png", "application/pdf"],
            },
          },
          {
            fieldId: "equipment_side_view_upload",
            name: "equipment_side_view_upload",
            type: "imageUpload",
            label: "Side View",
            required: true,
            editable: true,
            config: {
              maxFiles: 1,
              allowedTypes: ["image/jpeg", "image/png", "application/pdf"],
            },
          },
          {
            fieldId: "equipment_back_view_upload",
            name: "equipment_back_view_upload",
            type: "imageUpload",
            label: "Back View",
            required: true,
            editable: true,
            config: {
              maxFiles: 1,
              allowedTypes: ["image/jpeg", "image/png", "application/pdf"],
            },
          },
          {
            fieldId: "equipment_numberplate_view_upload",
            name: "equipment_numberplate_view_upload",
            type: "imageUpload",
            label: "Number Plate View",
            required: true,
            editable: true,
            config: {
              maxFiles: 1,
              allowedTypes: ["image/jpeg", "image/png", "application/pdf"],
            },
          },
        ],
        isLast: true,
      },
      {
        sectionId: "section_6_rolloff_photos",
        title: "Roll-Off Photos",
        order: 6,
        fields: [
          {
            fieldId: "rolloff_front_view_upload",
            name: "rolloff_front_view_upload",
            type: "imageUpload",
            label: "Front View",
            required: true,
            editable: true,
            config: {
              maxFiles: 1,
              allowedTypes: ["image/jpeg", "image/png", "application/pdf"],
            },
          },
          {
            fieldId: "rolloff_side_view_upload",
            name: "rolloff_side_view_upload",
            type: "imageUpload",
            label: "Side View",
            required: true,
            editable: true,
            config: {
              maxFiles: 1,
              allowedTypes: ["image/jpeg", "image/png", "application/pdf"],
            },
          },
          {
            fieldId: "rolloff_back_view_upload",
            name: "rolloff_back_view_upload",
            type: "imageUpload",
            label: "Back View",
            required: true,
            editable: true,
            config: {
              maxFiles: 1,
              allowedTypes: ["image/jpeg", "image/png", "application/pdf"],
            },
          },
          {
            fieldId: "rolloff_numberplate_view_upload",
            name: "rolloff_numberplate_view_upload",
            type: "imageUpload",
            label: "Number Plate View",
            required: true,
            editable: true,
            config: {
              maxFiles: 1,
              allowedTypes: ["image/jpeg", "image/png", "application/pdf"],
            },
          },
        ],
        isLast: true,
      },
      {
        sectionId: "section_7_container_shape",
        title: "Container Bottom Shape",
        order: 7,
        fields: [
          {
            fieldId: "container_bottom_shape",
            name: "container_bottom_shape",
            type: "customSelector",
            label: "Select bottom shape of container:",
            required: true,
            editable: true,
            defaultValue: "standard_rectangle",
            options: [
              {
                label: "Standard ( Rectangle )",
                value: "standard_rectangle",
                nextSectionId: "section_8_measurements",
              },
              {
                label: "Round-Bottom",
                value: "round_bottom",
                nextSectionId: "section_8_round_bottom_op_choice",
              },
            ],
          },
        ],
      },
      {
        sectionId: "section_8_measurements",
        title: "Truck Measurements - Main Area",
        order: 8,
        fields: [
          {
            fieldId: "length_in",
            name: "length_in",
            type: "measurement",
            label: "Length (L) in",
            placeholder: "Enter length in Inches",
            required: true,
            editable: true,
            ref_img: {
              url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/759d889f47e57110129cbf749f15c8a3bee44c09.png",
            },
          },
          {
            fieldId: "width_in",
            name: "width_in",
            type: "measurement",
            label: "Width (W) in",
            placeholder: "Enter width in Inches",
            required: true,
            editable: true,
            ref_img: {
              url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/c0e563a191a022a5fe58576527c75785931b2f07.png",
            },
          },
          {
            fieldId: "height_in",
            name: "height_in",
            type: "measurement",
            label: "Height (H) in",
            placeholder: "Enter height in Inches",
            required: true,
            editable: true,
            ref_img: {
              url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/5ff86652fbab53fb588f8e657e19b89d27783b5a.png",
            },
          },
          {
            fieldId: "total_surface_area",
            name: "total_surface_area",
            type: "calculated_view",
            label: "Total Surface Area:",
            editable: false,
            calculation: {
              formula: "length_in * width_in * height_in / 46656",
              variables: ["length_in", "width_in", "height_in"],
              unit: "CY",
            },
          },
        ],
        nextSectionId: "section_9_optional_area",
      },
      {
        sectionId: "section_9_optional_area",
        title: "Truck Measurements - Optional Area",
        order: 9,
        fields: [
          {
            fieldId: "over_cab_image",
            name: "over_cab_image",
            type: "imagedisplay",
            ref_img: {
              url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/79d5e4b872bce44a6816bad623b1d44a55a6eadb.png",
            },
          },
          {
            fieldId: "has_over_cab_section",
            name: "has_over_cab_section",
            type: "toggle",
            label: "Does the container have an over-cab section?",
            required: true,
            editable: true,
            defaultValue: true,
            options: [
              {
                label: "Yes",
                value: true,
                nextSectionId: "section_10_over_cab_measurements",
              },
              {
                label: "No",
                value: false,
                nextSectionId: "section_11_sloped_confirmation",
              },
            ],
          },
        ],
      },
      {
        sectionId: "section_10_over_cab_measurements",
        title: "Truck Measurements - Over Cab Section",
        order: 10,
        fields: [
          {
            fieldId: "over_cab_length_in",
            name: "over_cab_length_in",
            type: "measurement",
            label: "Length (L) in",
            placeholder: "Enter length in Inches",
            required: true,
            editable: true,
            ref_img: {
              url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/a9ebc512ed5cfa8f9ff78ac08c7738bb7ee6e909.png",
            },
          },
          {
            fieldId: "over_cab_width_in",
            name: "over_cab_width_in",
            type: "measurement",
            label: "Width (W) in",
            placeholder: "Enter width in Inches",
            required: true,
            editable: true,
            ref_img: {
              url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/5abdb1ef8d240e52ed4012d876f7ef7ff9d80774.png",
            },
          },
          {
            fieldId: "over_cab_height_in",
            name: "over_cab_height_in",
            type: "measurement",
            label: "Height (H) in",
            placeholder: "Enter height in Inches",
            required: true,
            editable: true,
            ref_img: {
              url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/96b57d307b7871e16157e4b16eaa7be19dfc48a7.png",
            },
          },
          {
            fieldId: "over_cab_total_surface_area",
            name: "over_cab_total_surface_area",
            type: "calculated_view",
            label: "Total Surface Area:",
            editable: false,
            calculation: {
              formula:
                "over_cab_length_in * over_cab_width_in * over_cab_height_in",
              variables: [
                "over_cab_length_in",
                "over_cab_width_in",
                "over_cab_height_in",
              ],
              unit: "CY",
            },
          },
        ],
        nextSectionId: "section_11_sloped_confirmation",
      },
      {
        sectionId: "section_11_sloped_confirmation",
        title: "Truck Measurements - Optional Area",
        order: 11,
        fields: [
          {
            fieldId: "sloped_section_image",
            name: "sloped_section_image",
            type: "imagedisplay",
            ref_img: {
              url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/e5dfe8a439ebaa0a35cbaa132f4daa10666d1f83.png",
            },
          },
          {
            fieldId: "has_sloped_section",
            name: "has_sloped_section",
            type: "toggle",
            label: "Does container have a sloped section? (Cut out)",
            required: true,
            editable: true,
            defaultValue: true,
            options: [
              {
                label: "Yes",
                value: true,
                nextSectionId: "section_12_sloped_measurements",
              },
              {
                label: "No",
                value: false,
                nextSectionId: "section_13_tailgate_confirmation",
              },
            ],
          },
        ],
      },
      {
        sectionId: "section_12_sloped_measurements",
        title: "Truck Measurements - Sloped (Cut Out)",
        order: 12,
        fields: [
          {
            fieldId: "sloped_length_in",
            name: "sloped_length_in",
            type: "measurement",
            label: "Length (L) in",
            placeholder: "Enter length in Inches",
            required: true,
            editable: true,
            ref_img: {
              url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/aac9b63af8386f8b5eac6f83e6737362caf6ff5d.png",
            },
          },
          {
            fieldId: "sloped_width_in",
            name: "sloped_width_in",
            type: "measurement",
            label: "Width (W) in",
            placeholder: "Enter width in Inches",
            required: true,
            editable: true,
            ref_img: {
              url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/306f9945b235c6b0b634c64c2c42eeb6a9340df2.png",
            },
          },
          {
            fieldId: "sloped_height_in",
            name: "sloped_height_in",
            type: "measurement",
            label: "Height (H) in",
            placeholder: "Enter height in Inches",
            required: true,
            editable: true,
            ref_img: {
              url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/9b21dd25278315c529696f43013cd3baee49fc7a.png",
            },
          },
          {
            fieldId: "sloped_total_surface_area",
            name: "sloped_total_surface_area",
            type: "calculated_view",
            label: "Total Surface Area:",
            editable: false,
            calculation: {
              formula: "sloped_length_in * sloped_width_in * sloped_height_in",
              variables: [
                "sloped_length_in",
                "sloped_width_in",
                "sloped_height_in",
              ],
              unit: "CY",
            },
          },
        ],
        nextSectionId: "section_13_tailgate_confirmation",
      },
      {
        sectionId: "section_13_tailgate_confirmation",
        title: "Truck Measurements - Optional Area",
        order: 13,
        fields: [
          {
            fieldId: "shortened_tailgate_image",
            name: "shortened_tailgate_image",
            type: "imagedisplay",
            ref_img: {
              url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/e84d2b18fcebc53d227936dbcc2f4d442ed901fe.png",
            },
          },
          {
            fieldId: "has_shortened_tailgate",
            name: "has_shortened_tailgate",
            type: "toggle",
            label:
              "Is the tailgate or solid rear panel shorter than the side walls, and do the side walls maintain the same height all the way to the back of the container? Refer to the example image for guidance.",
            required: true,
            editable: true,
            defaultValue: true,
            options: [
              {
                label: "Yes",
                value: true,
                nextSectionId: "section_14_tailgate_measurements",
              },
              {
                label: "No",
                value: false,
                nextSectionId: "section_15_frontgate_confirmation",
              },
            ],
          },
        ],
      },
      {
        sectionId: "section_14_tailgate_measurements",
        title: "Truck Measurements - Shortened Tailgate",
        order: 14,
        fields: [
          {
            fieldId: "tailgate_slope_x_in",
            name: "tailgate_slope_x_in",
            type: "measurement",
            label: "X slope in",
            placeholder: "Enter X slope in Inches",
            required: true,
            editable: true,
            ref_img: {
              url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/e18d23cbd53d4c96d7221389e346249013a0c6db.png",
            },
          },
          {
            fieldId: "tailgate_width_in",
            name: "tailgate_width_in",
            type: "measurement",
            label: "Width (W) in",
            placeholder: "Enter width in Inches",
            required: true,
            editable: true,
            ref_img: {
              url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/36a297c813469c1c1644ad96784415eb536f48a3.png",
            },
          },
          {
            fieldId: "tailgate_height_in",
            name: "tailgate_height_in",
            type: "measurement",
            label: "Height (H) in",
            placeholder: "Enter height in Inches",
            required: true,
            editable: true,
            ref_img: {
              url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/e72ca8bce25a72b7be6f587556ded936822382ae.png",
            },
          },
          {
            fieldId: "tailgate_surface_area",
            name: "tailgate_surface_area",
            type: "calculated_view",
            label: "Total Surface Area:",
            editable: false,
            calculation: {
              formula:
                "(tailgate_slope_x_in * tailgate_width_in * tailgate_height_in) / 2",
              variables: [
                "tailgate_slope_x_in",
                "tailgate_width_in",
                "tailgate_height_in",
              ],
              unit: "CY",
            },
          },
        ],
        nextSectionId: "section_15_frontgate_confirmation",
      },
      {
        sectionId: "section_15_frontgate_confirmation",
        title: "Truck Measurements - Optional Area",
        order: 15,
        fields: [
          {
            fieldId: "shortened_frontgate_image",
            name: "shortened_frontgate_image",
            type: "imagedisplay",
            ref_img: {
              url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/e84d2b18fcebc53d227936dbcc2f4d442ed901fe.png",
            },
          },
          {
            fieldId: "has_shortened_frontgate",
            name: "has_shortened_frontgate",
            type: "toggle",
            label:
              "Is the front gate or solid front panel shorter than the side walls, and do the side walls maintain the same height all the way to the back of the container? Refer to the example image for guidance.",
            required: true,
            editable: true,
            defaultValue: true,
            options: [
              {
                label: "Yes",
                value: true,
                nextSectionId: "section_16_frontgate_measurements",
              },
              {
                label: "No",
                value: false,
                nextSectionId: "section_17_add_deduct_choice",
              },
            ],
          },
        ],
      },
      {
        sectionId: "section_16_frontgate_measurements",
        title: "Truck Measurements - Shortened Front gate",
        order: 16,
        fields: [
          {
            fieldId: "frontgate_slope_x_in",
            name: "frontgate_slope_x_in",
            type: "measurement",
            label: "X slope in",
            placeholder: "Enter X slope in Inches",
            required: true,
            editable: true,
            ref_img: {
              url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/e18d23cbd53d4c96d7221389e346249013a0c6db.png",
            },
          },
          {
            fieldId: "frontgate_width_in",
            name: "frontgate_width_in",
            type: "measurement",
            label: "Width (W) in",
            placeholder: "Enter width in Inches",
            required: true,
            editable: true,
            ref_img: {
              url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/36a297c813469c1c1644ad96784415eb536f48a3.png",
            },
          },
          {
            fieldId: "frontgate_height_in",
            name: "frontgate_height_in",
            type: "measurement",
            label: "Height (H) in",
            placeholder: "Enter height in Inches",
            required: true,
            editable: true,
            ref_img: {
              url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/e72ca8bce25a72b7be6f587556ded936822382ae.png",
            },
          },
          {
            fieldId: "frontgate_surface_area",
            name: "frontgate_surface_area",
            type: "calculated_view",
            label: "Total Surface Area:",
            editable: false,
            calculation: {
              formula:
                "(frontgate_slope_x_in * frontgate_width_in * frontgate_height_in) / 2",
              variables: [
                "frontgate_slope_x_in",
                "frontgate_width_in",
                "frontgate_height_in",
              ],
              unit: "CY",
            },
          },
        ],
        nextSectionId: "section_17_add_deduct_choice",
      },
      {
        sectionId: "section_17_add_deduct_choice",
        title: "Truck Measurements - Optional Area",
        order: 17,
        fields: [
          {
            fieldId: "add_deduct_type",
            name: "add_deduct_type",
            type: "customSelector",
            label:
              "Are there any additional additions or deductions that apply to the container being measured? If so, please select the appropriate option. If none apply, select Next to continue.",
            required: true,
            editable: true,
            defaultValue: "addition",
            options: [
              { label: "Addition", value: "addition" },
              { label: "Deduction", value: "deduction" },
            ],
          },
        ],
        nextSectionId: "section_18_shape_choice",
      },
      {
        sectionId: "section_18_shape_choice",
        title: "Truck Measurements - Optional Area",
        order: 18,
        fields: [
          {
            fieldId: "add_deduct_shape",
            name: "add_deduct_shape",
            type: "customSelector",
            label:
              "Please select the correct shaped area for the addition or deduction needed. If the shape is not below, then select other.",
            required: true,
            editable: true,
            defaultValue: "rectangle",
            options: [
              {
                label: "Rectangle",
                value: "rectangle",
                ref_img: {
                  url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/b3f5e170eb8c8f30892f8c8250ebd4e4a1492b0d.png",
                },
                nextSectionId: "section_19_rectangle_area",
              },
              {
                label: "Sloped (Cut Out)",
                value: "sloped",
                ref_img: {
                  url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/e5dfe8a439ebaa0a35cbaa132f4daa10666d1f83.png",
                },
                nextSectionId: "section_19_sloped_area",
              },
              {
                label: "Other",
                value: "other",
                conditionalNextSection: {
                  basedOnField: "add_deduct_type",
                  mapping: {
                    addition: "section_19_additional_area",
                    deduction: "section_19_deduction_area",
                  },
                },
              },
            ],
          },
        ],
      },
      {
        sectionId: "section_19_rectangle_area",
        title: "Truck Measurements - Rectangle Area",
        order: 19,
        fields: [
          {
            fieldId: "add_deduct_rectangle_length_in",
            name: "add_deduct_rectangle_length_in",
            type: "measurement",
            label: "Length (L) in",
            placeholder: "Enter length in Inches",
            required: true,
            editable: true,
            ref_img: {
              url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/0cececc3524d375447be9f0bf3faaeeea8e152e2.png",
            },
          },
          {
            fieldId: "add_deduct_rectangle_width_in",
            name: "add_deduct_rectangle_width_in",
            type: "measurement",
            label: "Width (W) in",
            placeholder: "Enter width in Inches",
            required: true,
            editable: true,
            ref_img: {
              url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/f62374e03b18484833daaad278ca4df2235ecfd3.png",
            },
          },
          {
            fieldId: "add_deduct_rectangle_height_in",
            name: "add_deduct_rectangle_height_in",
            type: "measurement",
            label: "Height (H) in",
            placeholder: "Enter height in Inches",
            required: true,
            editable: true,
            ref_img: {
              url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/3caad27be2c5b475d2ac7c80f5df6da0072a2d59.png",
            },
          },
          {
            fieldId: "add_deduct_rectangle_area",
            name: "add_deduct_rectangle_area",
            type: "calculated_view",
            label: "Total Surface Area:",
            editable: false,
            calculation: {
              formula:
                "add_deduct_rectangle_length_in * add_deduct_rectangle_width_in * add_deduct_rectangle_height_in",
              variables: [
                "add_deduct_rectangle_length_in",
                "add_deduct_rectangle_width_in",
                "add_deduct_rectangle_height_in",
              ],
              unit: "CY",
            },
          },
        ],
        isLast: true,
      },
      {
        sectionId: "section_19_sloped_area",
        title: "Truck Measurements - Sloped (Cut Out)",
        order: 19,
        fields: [
          {
            fieldId: "add_deduct_sloped_length_in",
            name: "add_deduct_sloped_length_in",
            type: "measurement",
            label: "Length (L) in",
            placeholder: "Enter length in Inches",
            required: true,
            editable: true,
            ref_img: {
              url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/aac9b63af8386f8b5eac6f83e6737362caf6ff5d.png",
            },
          },
          {
            fieldId: "add_deduct_sloped_width_in",
            name: "add_deduct_sloped_width_in",
            type: "measurement",
            label: "Width (W) in",
            placeholder: "Enter width in Inches",
            required: true,
            editable: true,
            ref_img: {
              url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/306f9945b235c6b0b634c64c2c42eeb6a9340df2.png",
            },
          },
          {
            fieldId: "add_deduct_sloped_height_in",
            name: "add_deduct_sloped_height_in",
            type: "measurement",
            label: "Height (H) in",
            placeholder: "Enter height in Inches",
            required: true,
            editable: true,
            ref_img: {
              url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/9b21dd25278315c529696f43013cd3baee49fc7a.png",
            },
          },
          {
            fieldId: "add_deduct_sloped_area",
            name: "add_deduct_sloped_area",
            type: "calculated_view",
            label: "Total Surface Area:",
            editable: false,
            calculation: {
              formula:
                "add_deduct_sloped_length_in * add_deduct_sloped_width_in * add_deduct_sloped_height_in",
              variables: [
                "add_deduct_sloped_length_in",
                "add_deduct_sloped_width_in",
                "add_deduct_sloped_height_in",
              ],
              unit: "CY",
            },
          },
        ],
        isLast: true,
      },
      {
        sectionId: "section_19_additional_area",
        title: "Truck Measurements - Additional area",
        order: 19,
        fields: [
          {
            fieldId: "add_deduct_other_add_length_in",
            name: "add_deduct_other_add_length_in",
            type: "measurement",
            label: "Length (L) in",
            placeholder: "Enter length in Inches",
            required: true,
            editable: true,
          },
          {
            fieldId: "add_deduct_other_add_height_in",
            name: "add_deduct_other_add_height_in",
            type: "measurement",
            label: "Height (H) in",
            placeholder: "Enter height in Inches",
            required: true,
            editable: true,
          },
          {
            fieldId: "add_deduct_other_add_width_in",
            name: "add_deduct_other_add_width_in",
            type: "measurement",
            label: "Width (W) in",
            placeholder: "Enter width in Inches",
            required: true,
            editable: true,
          },
          {
            fieldId: "add_deduct_other_add_area",
            name: "add_deduct_other_add_area",
            type: "calculated_view",
            label: "Total Surface Area:",
            editable: false,
            calculation: {
              formula:
                "add_deduct_other_add_length_in * add_deduct_other_add_height_in * add_deduct_other_add_width_in",
              variables: [
                "add_deduct_other_add_length_in",
                "add_deduct_other_add_height_in",
                "add_deduct_other_add_width_in",
              ],
              unit: "CY",
            },
          },
        ],
        isLast: true,
      },
      {
        sectionId: "section_19_deduction_area",
        title: "Truck Measurements - Deduction area",
        order: 19,
        fields: [
          {
            fieldId: "add_deduct_other_deduct_length_in",
            name: "add_deduct_other_deduct_length_in",
            type: "measurement",
            label: "Length (L) in",
            placeholder: "Enter length in Inches",
            required: true,
            editable: true,
          },
          {
            fieldId: "add_deduct_other_deduct_height_in",
            name: "add_deduct_other_deduct_height_in",
            type: "measurement",
            label: "Height (H) in",
            placeholder: "Enter height in Inches",
            required: true,
            editable: true,
          },
          {
            fieldId: "add_deduct_other_deduct_width_in",
            name: "add_deduct_other_deduct_width_in",
            type: "measurement",
            label: "Width (W) in",
            placeholder: "Enter width in Inches",
            required: true,
            editable: true,
          },
          {
            fieldId: "add_deduct_other_deduct_area",
            name: "add_deduct_other_deduct_area",
            type: "calculated_view",
            label: "Total Surface Area:",
            editable: false,
            calculation: {
              formula:
                "add_deduct_other_deduct_length_in * add_deduct_other_deduct_height_in * add_deduct_other_deduct_width_in",
              variables: [
                "add_deduct_other_deduct_length_in",
                "add_deduct_other_deduct_height_in",
                "add_deduct_other_deduct_width_in",
              ],
              unit: "CY",
            },
          },
        ],
        isLast: true,
      },
      {
        sectionId: "section_8_round_bottom_op_choice",
        title: "Truck Measurements - Optional Area",
        order: 8,
        fields: [
          {
            fieldId: "round_bottom_op_type",
            name: "round_bottom_op_type",
            type: "customSelector",
            label:
              "Select which type of Round-Bottom container is being measured.",
            required: true,
            editable: true,
            defaultValue: "addition",
            options: [
              { label: "Addition", value: "addition" },
              { label: "Deduction", value: "deduction" },
            ],
          },
        ],
        nextSectionId: "section_9_round_bottom_style_choice",
      },
      {
        sectionId: "section_9_round_bottom_style_choice",
        title: "Truck Measurements - Round-Bottom",
        order: 9,
        fields: [
          {
            fieldId: "round_bottom_style",
            name: "round_bottom_style",
            type: "customSelector",
            label:
              "Select which type of Round-Bottom container is being measured..",
            required: true,
            editable: true,
            defaultValue: "flat_sides",
            options: [
              {
                label: "Round-Bottom (with flat sides)",
                value: "flat_sides",
                ref_img: {
                  url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/cdd747a0332c3a8949750593c788d88ba17b988f.png",
                },
                nextSectionId: "section_10_round_bottom_flat_measurements",
              },
              {
                label: "Round-Bottom (with curved sides)",
                value: "curved_sides",
                ref_img: {
                  url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/7ee26fc29416fa16cfe9d65562977a7842f57bf7.png",
                },
                nextSectionId: "section_10_round_bottom_curved_measurements",
              },
            ],
          },
        ],
      },
      {
        sectionId: "section_10_round_bottom_flat_measurements",
        title: "Truck Measurements - Round Bottom (Flat)",
        order: 10,
        fields: [
          {
            fieldId: "rb_flat_h_flat_in",
            name: "rb_flat_h_flat_in",
            type: "measurement",
            label: "H flat in",
            placeholder: "Enter H flat in Inches",
            required: true,
            editable: true,
            ref_img: {
              url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/ff3913d03bcce2d12dbd39e0ab9b46a94813d236.png",
            },
          },
          {
            fieldId: "rb_flat_width_in",
            name: "rb_flat_width_in",
            type: "measurement",
            label: "Width (W) in",
            placeholder: "Enter width in Inches",
            required: true,
            editable: true,
            ref_img: {
              url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/faee8cd10eac84e5b7e1eaf9117ba75db3735577.png",
            },
          },
          {
            fieldId: "rb_flat_height_in",
            name: "rb_flat_height_in",
            type: "measurement",
            label: "Height (H) in",
            placeholder: "Enter height in Inches",
            required: true,
            editable: true,
            ref_img: {
              url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/ff3913d03bcce2d12dbd39e0ab9b46a94813d236.png",
            },
          },
          {
            fieldId: "rb_flat_surface_area",
            name: "rb_flat_surface_area",
            type: "calculated_view",
            label: "Total Surface Area:",
            editable: false,
            calculation: {
              formula:
                "(rb_flat_h_flat_in * rb_flat_width_in * rb_flat_height_in) * 0.85",
              variables: [
                "rb_flat_h_flat_in",
                "rb_flat_width_in",
                "rb_flat_height_in",
              ],
              unit: "CY",
            },
          },
        ],
        isLast: true,
      },
      {
        sectionId: "section_10_round_bottom_curved_measurements",
        title: "Truck Measurements-Round Bottom (Curved)",
        order: 10,
        fields: [
          {
            fieldId: "rb_curved_length_in",
            name: "rb_curved_length_in",
            type: "measurement",
            label: "Length (L) in",
            placeholder: "Enter Length in Inches",
            required: true,
            editable: true,
            ref_img: {
              url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/c1e23613b3db8417f22b6b2523cd01dd85c1aad3.png",
            },
          },
          {
            fieldId: "rb_curved_width_in",
            name: "rb_curved_width_in",
            type: "measurement",
            label: "Width (W) in",
            placeholder: "Enter width in Inches",
            required: true,
            editable: true,
            ref_img: {
              url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/7e9f48584d0847518e66e110d04832a4102c75eb.png",
            },
          },
          {
            fieldId: "rb_curved_height_in",
            name: "rb_curved_height_in",
            type: "measurement",
            label: "Height (H) in",
            placeholder: "Enter height in Inches",
            required: true,
            editable: true,
            ref_img: {
              url: "https://ajvtgocuqbacesqppilm.supabase.co/storage/v1/object/public/demo/38f0ebf0a59f83fa72d872aea57f1288c922da9d.png",
            },
          },
          {
            fieldId: "rb_curved_surface_area",
            name: "rb_curved_surface_area",
            type: "calculated_view",
            label: "Total Surface Area:",
            editable: false,
            calculation: {
              formula:
                "(rb_curved_length_in * rb_curved_width_in * rb_curved_height_in) * 0.75",
              variables: [
                "rb_curved_length_in",
                "rb_curved_width_in",
                "rb_curved_height_in",
              ],
              unit: "CY",
            },
          },
        ],
        isLast: true,
      },
    ],
  });
});

export default router;
